AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dev

# Parameters:
#   AmiId:
#     Type: AWS::EC2::Image::Id
#     Description: The AMI ID for the instance

#   InstanceType:
#     Type: String
#     Description: The EC2 instance type

#   MyIp:
#     Type: String
#     Description: Your public IP address for SSH access

#   MyVpc:
#     Type: String
#     Description: Your public IP address for SSH access

Globals:
  Function:
    Architectures: [ x86_64 ]
    Runtime: java21
    MemorySize: 1792
    Timeout: 900
    EphemeralStorage:
      Size: 512
    PropagateTags: true

Resources:
  traceLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: traceLambda
      Description: 'Lambda function for encoding'
      PackageType: Zip
      CodeUri: ./
      Handler: lambda.Main::handleRequest
      Policies:
        - AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: NONE
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Ref LogGroup



  # SecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: Allow SSH access
  #     VpcId: !Ref MyVpc
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 22
  #         ToPort: 22
  #         CidrIp: !Sub '${MyIp}/32'
  #       - IpProtocol: icmp
  #         FromPort: -1
  #         ToPort: -1
  #         CidrIp: !Sub '${MyIp}/32'
  #     SecurityGroupEgress:
  #       - IpProtocol: -1
  #         CidrIp: 0.0.0.0/0

  # controller:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     ImageId: !Ref AmiId
  #     InstanceType: !Ref InstanceType
  #     KeyName: !Ref NewKeyPair
  #     SecurityGroupIds: [ !Ref SecurityGroup ]

  # NewKeyPair:
  #   Type: AWS::EC2::KeyPair
  #   Properties:
  #     KeyName: !Sub '${AWS::StackName}-KeyPair'

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/trace'
      RetentionInDays: 30

# noinspection YamlUnresolvedReferences
Outputs:
  # KeyPairName:
  #   Description: The name of the newly created key pair
  #   Value: !Ref NewKeyPair
  # controller:
  #   Description: "Controller Node ip"
  #   Value: !GetAtt controller.PublicIp
  traceLambda:
    Description: "Function ARN"
    Value: !GetAtt traceLambda.Arn
  traceLambdahost:
    Description: "Lambda URL"
    Value: !GetAtt traceLambdaUrl.FunctionUrl
