AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'CloudEventTrace Function URL Configuration'

Globals:
  Function:
    Architectures: [x86_64]
    Runtime: java21
    MemorySize: 1792
    Timeout: 900
#    EphemeralStorage
#      Size: 512
#    PropagateTags: true

Resources:
  CloudEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda'
      Description: 'Lambda function'
      PackageType: Zip
      CodeUri: './'
      Handler: lambda.Entry::handleRequest
      FunctionUrlConfig:
        AuthType: NONE
      LoggingConfig:
        LogFormat: Text
        LogGroup: !Ref LogGroup

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/${AWS::StackName}'
      RetentionInDays: 14

Outputs:
  FunctionUrl:
    Description: 'Lambda Function URL'
    Value: !GetAtt CloudEventFunctionUrl.FunctionUrl
  FunctionArn:
    Description: 'Lambda Function ARN'
    Value: !GetAtt CloudEventFunction.Arn




